# The prettiest theme helix has to offer
theme = "bogster"

[editor]

# Show rulers to encourage max line widths
rulers = [80]

# Elvish for commands
shell = ['elvish', '-c']

# Kind of like tabs
bufferline = 'always'

# Colors!
true-color = true
color-modes = true
undercurl = true

# Do not be noisy
auto-completion = true

# Doesn't usually want what I do
auto-pairs = false

[editor.lsp]
auto-signature-help = true

[editor.cursor-shape]

# Have more distinct cursor shapes
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]

# Hidden files should be shown in the picker (still considers .gitignore)
hidden = false
git-ignore = true

# Do not follow symlinks
follow-symlinks = false

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

V = ["goto_first_nonwhitespace", "extend_to_line_end"]
D = ["ensure_selections_forward", "extend_to_line_end"]
x = "extend_line"

# Additional commands for the space menu
[keys.normal.space]
w = ":write"
q = ":quit"
x = ":write-quit"
c = ":buffer-close"

# A menu for editor toggle commands
[keys.normal."="]
s = ":toggle-option soft-wrap.enable"
h = ":toggle-option lsp.auto-signature-help"

[keys.select]
";" = ["collapse_selection", "normal_mode"]
x = "extend_line"
V = "extend_to_line_end"

[editor.statusline]
right = ["diagnostics", "version-control", "selections", "position", "file-encoding"]

[editor.soft-wrap]
enable = false
wrap-indicator = ""
wrap-at-text-width = true
