[[language]]
name = "yaml"
auto-format = true
formatter = { command = "strip-whitespace" }
config = { yaml = { keyOrdering = false } }

[[language]]
name = "toml"
auto-format = true
formatter = { command = "strip-whitespace" }

[[language]]
name = "python"
auto-format = true
formatter = { command = "strip-whitespace" }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "strip-whitespace" }
